CREATE TABLE [dbo].[Employees] (
    [Id]                     INT           NOT NULL,
    [PreviousEmployment]     VARCHAR (300) NULL,
    [ContractSignedAt]       DATETIME      NULL,
    [BranchId]               INT           NOT NULL,
    [OnSite]                 BIT           NULL,
    [Comments]               VARCHAR (MAX) NULL,
    [Photo]                  VARCHAR (70)  NULL,
    [Score]                  INT           NULL,
    [DailyReportNotRequired] BIT           CONSTRAINT [DF_employees_drNotRequired] DEFAULT ((0)) NOT NULL,
    [LastHrmContactAt]       DATETIME      NULL,
    [IsPartTime]             BIT           DEFAULT ((0)) NOT NULL,
    [BucketTaskId]           BIGINT        DEFAULT (NULL) NULL,
    [DefaultBucketJobText]   VARCHAR (500) DEFAULT ('') NOT NULL,
    [DefaultBucketTaskTitle] VARCHAR (255) DEFAULT ('') NOT NULL,
    [RecruitedByUserId]      INT           NULL,
    [VendorId]               INT           NULL,
    [RecruitSourceId]        INT           NULL,
    [FirstWorkingDate]       DATETIME      DEFAULT (getdate()) NOT NULL,
    [LastWorkingDate]        DATETIME      NULL,
    [IsIntern]               BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_employeeID] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [bucket_task_id] FOREIGN KEY ([BucketTaskId]) REFERENCES [dbo].[Tasks] ([taskID]),
    CONSTRAINT [FK_Employees_Id_Users_Id] FOREIGN KEY ([Id]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_employees_lookup_branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[LookupBranch] ([Id]),
    CONSTRAINT [FK_Employees_RecruitedByUserId] FOREIGN KEY ([RecruitedByUserId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Employees_RecruitSourceId] FOREIGN KEY ([RecruitSourceId]) REFERENCES [dbo].[LookupRecruitSources] ([Id]),
    CONSTRAINT [FK_Employees_VendorId] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[LookupVendors] ([Id])
);

