CREATE TABLE [dbo].[task_reestimations] (
    [Id]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [TaskId]         BIGINT        NOT NULL,
    [Status]         INT           DEFAULT ((1)) NOT NULL,
    [OldLimit]       INT           NULL,
    [OldDueDate]     DATETIME      NULL,
    [NewLimit]       INT           NULL,
    [NewDueDate]     DATETIME      NULL,
    [CreateReason]   VARCHAR (MAX) NOT NULL,
    [DeclineReason]  VARCHAR (MAX) NULL,
    [CreatedById]    INT           NOT NULL,
    [CreatedDate]    DATETIME      NOT NULL,
    [ApprovedByIdTm] INT           NULL,
    [ApprovedDateTm] DATETIME      NULL,
    [DeclinedByIdTm] INT           NULL,
    [DeclinedDateTm] DATETIME      NULL,
    [ApprovedByIdPm] INT           NULL,
    [ApprovedDatePm] DATETIME      NULL,
    [DeclinedByIdPm] INT           NULL,
    [DeclinedDatePm] DATETIME      NULL,
    CONSTRAINT [PK_task_reestimations_ID] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_task_reestimations_tasks_taskID] FOREIGN KEY ([TaskId]) REFERENCES [dbo].[Tasks] ([taskID]),
    CONSTRAINT [FK_task_reestimations_users_userID_approved_PM] FOREIGN KEY ([ApprovedByIdPm]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_task_reestimations_users_userID_approved_TM] FOREIGN KEY ([ApprovedByIdTm]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_task_reestimations_users_userID_created] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_task_reestimations_users_userID_declined_PM] FOREIGN KEY ([DeclinedByIdPm]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_task_reestimations_users_userID_declined_TM] FOREIGN KEY ([DeclinedByIdTm]) REFERENCES [dbo].[Users] ([Id])
);

